fix: update cdk commands

diff --git a/run b/run
--- a/run
+++ b/run
@@ -3,20 +3,20 @@
 set -euox pipefail
 
 # Source the .env file if it exists
-[ -f .env ] && source .env || echo ".env file not found!" && exit 1
+[ -f .env ] && source .env # || echo ".env file not found!" && exit 1
 
 export AWS_PROFILE=sandbox
 export AWS_REGION=us-east-1
 export AWS_DEFAULT_REGION=${AWS_REGION}
 
 # aws account id/hash used to make a unique, but consistent bucket name
-# export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --profile $AWS_PROFILE --query "Account" --output text)
+export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --profile $AWS_PROFILE --query "Account" --output text)
 
 # Cache AWS account ID for 10 hours using bash-cache
 # AWS_ACCOUNT_ID=$(bc::cache 10h aws sts get-caller-identity --profile $AWS_PROFILE --query "Account" --output text)
 
 # Cache AWS account ID for 10 hours using our custom function
-AWS_ACCOUNT_ID=$(get-cached-aws-account-id 10)
+# AWS_ACCOUNT_ID=$(get-cached-aws-account-id 10)
 AWS_ACCOUNT_ID_HASH=$(echo -n "${AWS_ACCOUNT_ID}" | sha256sum | cut -c5-8)
 export S3_BUCKET_NAME="ml-school-bucket-${AWS_ACCOUNT_ID_HASH}" # ml-school-bucket-6721
 
@@ -25,7 +25,7 @@ THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
 # Data file path on your local machine
 DATA_FILE_PATH="$THIS_DIR/data/penguins.csv"
-if ! [ -f "$DATA_FILE_PATH" ]; then
+if [ ! -f "$DATA_FILE_PATH" ]; then
     echo "Data file not found: $DATA_FILE_PATH"
     echo "Downloading data..."
     uv run script/download_data.py
@@ -37,7 +37,7 @@ fi
 ##########################
 
 function run-pipeline () {
-    if [[ "$1" == "--local" ]]; then
+    if [[ "${1:-}" == "--local" ]]; then
         export LOCAL_MODE=1
     fi
     uv run pipeline.py
@@ -52,11 +52,11 @@ function cdk-bootstrap () {
 }
 
 function cdk-deploy () {
-    uv run -- cdk deploy --app 'python cdk_app.py' '*' --profile $AWS_PROFILE --region $AWS_REGION
+    cdk deploy --app 'uv run --script cdk_app.py' '*' --profile $AWS_PROFILE --region $AWS_REGION
 }
 
 function cdk-destroy () {
-    uv run -- cdk destroy --app 'python cdk_app.py' '*' --profile $AWS_PROFILE --region $AWS_REGION
+    cdk destroy --app 'uv run --script cdk_app.py' '*' --profile $AWS_PROFILE --region $AWS_REGION
 }
 
 
